Add structured data for python tracebacks for syslog messages (#15291)
This commit ensures that python tracebacks are properly sent to
remote syslog server and inserted into our own log files via
syslog-ng. Records are converted to single-line and tracebacks
and associated stack information are converted to parameterized
JSON data to allow for easier automated parsing of log entries.

Messages will have format as follows:

```
<message> @cee:{"TNLOG": {"exception": <exception>, ...}}
```

Fields for the TNLOG entry are:
```
type: "PYTHON_EXCEPTION"
exception: <traceback information>
stack: (optional) <stack information
```